### 上传文件
POST {{media_host}}/media/upload/coursefile
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="filedata"; filename="165917-16953731571c11.jpg"
Content-Type: application/octet-stream

< C:/Users/zhour/Pictures/165917-16953731571c11.jpg
